import { Language } from '../types';

export const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.categories': 'Categories',
    'nav.cart': 'My Cart',
    'nav.admin': 'Admin Portal',
    'hero.title': 'Fast Fashion, Habesha Style',
    'hero.subtitle': 'Discover Sheger\'s trendiest outfits inspired by global designs and authentic Ethiopian hand-woven heritage.',
    'hero.cta': 'Shop Latest Collection',
    'hero.badge': 'NEW ARRIVALS 2026',
    'search.placeholder': 'Search dresses, hoodies, traditional kemis...',
    'product.price': 'ETB',
    'product.size': 'Size',
    'product.color': 'Color',
    'product.brand': 'Brand',
    'product.addToCart': 'Add to Cart',
    'product.quickView': 'Quick View',
    'product.orderTelegram': 'Order on Telegram',
    'product.orderWhatsApp': 'Order on WhatsApp',
    'product.callToOrder': 'Call to Order',
    'product.outOfStock': 'Out of Stock',
    'product.lowStock': 'Low Stock!',
    'product.description': 'Description',
    'cart.title': 'Shopping Cart',
    'cart.empty': 'Your cart is empty. Let\'s explore some styles!',
    'cart.total': 'Subtotal',
    'cart.checkoutHeader': 'Complete Your Order',
    'cart.checkoutSub': 'Orders are processed through Telegram, WhatsApp, or Direct Call. No online payment required.',
    'cart.customerName': 'Full Name',
    'cart.customerPhone': 'Phone Number (e.g. 0912...)',
    'cart.customerCity': 'Select City / Location',
    'cart.customerCityPlaceholder': 'Select your location',
    'cart.orderNotes': 'Special Requests (Size, color adjustments, delivery time...)',
    'cart.sendTelegram': 'Submit & Chat on Telegram (@yared_abegaz)',
    'cart.sendWhatsApp': 'Submit & Chat on WhatsApp (+15714749554)',
    'cart.sendCall': 'Direct Call: 0995967804',
    'cart.successMsg': 'Order Logged Successfully! Re-routing you to your messaging app...',
    'admin.dashboard': 'Admin Dashboard',
    'admin.viewStore': 'Back to Store',
    'seo.localShippingTitle': 'Local Shipping & Delivery Info',
    'seo.localShippingDesc': 'Enjoy fast delivery inside Addis Ababa (Bole, Shiro Meda, Megenagna, Piassa) within 24 hours. For regional cities (Hawassa, Bahir Dar, Mekele, Adama, Dire Dawa, Gondar, Jimma), we ship securely via trusted EMS or regional public transport with real-time updates.'
  },
  am: {
    'nav.home': 'ዋና ገጽ',
    'nav.categories': 'ምድቦች',
    'nav.cart': 'ጋሪዬ',
    'nav.admin': 'የአስተዳዳሪ ገጽ',
    'hero.title': 'ዘመናዊ ፋሽን፣ በሐበሻ ስታይል',
    'hero.subtitle': 'በዓለም አቀፍ ዲዛይኖች እና በእውነተኛ የኢትዮጵያ በእጅ የተሸመኑ አልባሳት የተሰሩ ምርጥ ፋሽኖችን እዚህ ያግኙ።',
    'hero.cta': 'አዲሱን ስብስብ ይግዙ',
    'hero.badge': 'የ2018 አዲስ ስብስቦች',
    'search.placeholder': 'ቀሚሶችን፣ ሁዲዎችን፣ ባህላዊ ቀሚሶችን እዚህ ይፈልጉ...',
    'product.price': 'ብር',
    'product.size': 'መጠን',
    'product.color': 'ቀለም',
    'product.brand': 'ብራንድ',
    'product.addToCart': 'ወደ ጋሪ ጨምር',
    'product.quickView': 'በቅርብ እይ',
    'product.orderTelegram': 'በቴሌግራም እዘዝ',
    'product.orderWhatsApp': 'በዋትስአፕ እዘዝ',
    'product.callToOrder': 'ደውለው ይዘዙ',
    'product.outOfStock': 'ያለቀ',
    'product.lowStock': 'ለማለቅ የተቃረበ!',
    'product.description': 'የእቃው ዝርዝር መግለጫ',
    'cart.title': 'የግዢ ጋሪ',
    'cart.empty': 'ጋሪዎ ባዶ ነው። አዳዲስ ስታይሎችን ይመልከቱ!',
    'cart.total': 'ጠቅላላ ድምር',
    'cart.checkoutHeader': 'ትዕዛዝዎን ያጠናቅቁ',
    'cart.checkoutSub': 'ትዕዛዞች በቴሌግራም፣ በዋትስአፕ ወይም በቀጥታ ጥሪ ይስተናገዳሉ። የኢንተርኔት ክፍያ አያስፈልግም።',
    'cart.customerName': 'ሙሉ ስም',
    'cart.customerPhone': 'የስልክ ቁጥር (ምሳሌ 0912...)',
    'cart.customerCity': 'ከተማ / መገኛ ቦታ',
    'cart.customerCityPlaceholder': 'መገኛ ቦታዎን ይምረጡ',
    'cart.orderNotes': 'ልዩ ትዕዛዝ ካለዎት (መጠን፣ ቀለም ማስተካከያ፣ የመረከቢያ ሰዓት...)',
    'cart.sendTelegram': 'በቴሌግራም አጠናቅቅና አውራ (@yared_abegaz)',
    'cart.sendWhatsApp': 'በዋትስአፕ አጠናቅቅና አውራ (+15714749554)',
    'cart.sendCall': 'በስልክ ደውለው ይዘዙ: 0995967804',
    'cart.successMsg': 'ትዕዛዝዎ በተሳካ ሁኔታ ተመዝግቧል! ወደ መላኪያ መተግበሪያዎ እያመራንዎት ነው...',
    'admin.dashboard': 'የአስተዳዳሪ ሰሌዳ',
    'admin.viewStore': 'ወደ ሱቅ ተመለስ',
    'seo.localShippingTitle': 'የሀገር ውስጥ መላኪያ እና አቅርቦት መረጃ',
    'seo.localShippingDesc': 'በአዲስ አበባ (ቦሌ፣ ሽሮ ሜዳ፣ መገናኛ፣ ፒያሳ) ውስጥ በ24 ሰዓታት ፈጣን አቅርቦት ይደሰቱ። ለክፍለ ሀገር ከተሞች (ሀዋሳ፣ ባህር ዳር፣ መቐለ፣ አዳማ፣ ድሬዳዋ፣ ጎንደር፣ ጅማ) አስተማማኝ በሆነው በኢኤምኤስ (EMS) ወይም በሕዝብ ትራንስፖርት በፍጥነት እናደርሳለን።'
  }
};

export const ETHIOPIAN_CITIES = [
  'Addis Ababa (Bole)',
  'Addis Ababa (Megenagna)',
  'Addis Ababa (Shiro Meda)',
  'Addis Ababa (Piassa / Merkato)',
  'Addis Ababa (Sarbet)',
  'Addis Ababa (Lideta / Mexico)',
  'Hawassa',
  'Bahir Dar',
  'Adama (Nazreth)',
  'Dire Dawa',
  'Mekele',
  'Gondar',
  'Jimma',
  'Dessie',
  'Harar',
  'Sodo',
  'Arba Minch',
  'Debre Birhan'
];
